### ISSUE TITLE
"statik --project ." encounter error

### ISSUE THREAD

**Issue by luckypoem** [thanethomson/blog#1]
hi.

root@localhost:/usr/local/statik-site/thanethomson.com/data/Post# cat 2017-03-27-test-1.md
---
title: 测试1
slug: test-1
summary: >
  点击标题，
  看全文。
date: 2017-03-27T15:15:00
tags:
  - misc1
  - misc2
  - misc3
---
 
这是测试1.

看看如何？
root@localhost:/usr/local/statik-site/thanethomson.com/data/Post# cd ../..
root@localhost:/usr/local/statik-site/thanethomson.com# statik --project .
Project path configured as: /usr/local/statik-site/thanethomson.com
Using encoding: utf-8
Unable to clean up properly: 'NoneType' object has no attribute 'shutdown'
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/statik/project.py", line 117, in generate
    self.db.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file cmdline.py, line 113
root@localhost:/usr/local/statik-site/thanethomson.com# ls
assets      config.yml  models  public-old   README.md  views
bower.json  data        public  public-old2  templates
root@localhost:/usr/local/statik-site/thanethomson.com#

the test-1.md is in chinese.how to make ur app support chinese posts?
tks

**Comment by thanethomson** [comment]
Make sure you set your encoding in the `config-dev.yml` file. Which encoding do you normally use? The `config-dev.yml` file is set, by default, to use `utf-8`.

**Comment by luckypoem** [comment]
hi.

actually ,it's using utf-8,i didn't change config.yml.just rename config-dev.yml to config.yml
root@localhost:/usr/local/statik-site/thanethomson.com# cat  config.yml 
project-name: thanethomson.com
base-path: /
encoding: utf-8
context:
  static:
    site-description: >
      I enjoy creating useful things for people, and sometimes I like to
      write about stuff too.
    production: false
    disqus-user-id: useridhere
root@localhost:/usr/local/statik-site/thanethomson.com#

**Comment by thanethomson** [comment]
Check this out: http://stackoverflow.com/questions/3883573/encoding-error-in-python-with-chinese-characters

**Comment by luckypoem** [comment]
i checked http://stackoverflow.com/questions/3883573/encoding-error-in-python-with-chinese-characters ,
it didn't work.can u pls try to publish a chinese post in your blog to experience the issue and find a solution?

thank u very much.

u can use the contents of my post: 2017-03-27-test-1.md above.

**Comment by thanethomson** [comment]
So I spent some time looking into this this morning, and I'm unfortunately just not familiar enough with Chinese encoding to be able to help much more here. I tried several different encodings (`big5`, `big5hkscs`, `gb18030`, `gbk`, and a few others) and none of them worked for your text.

Which encoding does your text editor use when you're typing text documents? See [this list](https://docs.python.org/2.4/lib/standard-encodings.html).

**Comment by luckypoem** [comment]
somebody told me to insert sys.setdefaultencoding('utf8') into  __main__.py ,but i checked https://github.com/thanethomson/statik/tree/master/statik ,i didn't find __main__.py ,so which file to modify to insert sys.setdefaultencoding('utf8') in the py files in https://github.com/thanethomson/statik/tree/master/statik ?

**Comment by thanethomson** [comment]
No, I don't think that will work. That's the same as setting the `encoding` parameter in your `config.yml` file to `utf8`.

What you need is the appropriate codec that understands that particular character set.

**Comment by thanethomson** [comment]
I've tried using the [chardet](https://pypi.python.org/pypi/chardet) library to detect the encoding for your file, but it claims that the encoding is `utf8`. It's hard, because the encoding depends on several factors, as far as I understand it:

* The encoding that your editor uses.
* The encoding that **Statik** uses (`utf8` by default, but customisable).
* The encoding that your operating system uses.

Which OS are you using?

**Comment by luckypoem** [comment]
the editor i uses in linux vps is nano.i don't know where to check its encoding.
The encoding that Statik uses is uft8
i don't know where to check The encoding that my operating system(ubuntu vps) uses.

**Comment by luckypoem** [comment]
somebody told me to insert:

# encoding=utf8  
import sys  
  
reload(sys)  
sys.setdefaultencoding('utf8')  

into py files.i don't know which py files to modify.

**Comment by thanethomson** [comment]
No, using `sys.setdefaultencoding` is [heavily discouraged](http://stackoverflow.com/questions/3828723/why-should-we-not-use-sys-setdefaultencodingutf-8-in-a-py-script). Python 3 uses `utf8` by default, so manually setting it to `utf8` again won't have any effect (apparently Python 3 even throws an error if you try use `sys.setdefaultencoding`).

Which version of Python are you using? Have you tried using Python 3? Also, have you checked what your system's default encoding is? Which OS are you using? (Because then I might be able to help in finding out which encoding your OS uses).

**Comment by luckypoem** [comment]
i uninstalled statik.then,
root@localhost:/usr/local/statik-site# ls
build         dist        MANIFEST.in  requirements.txt  setup.py         tests
CHANGELOG.md  examples    README.md    scripts           statik           thanethomson.com
CONTRIBUTORS  LICENSE.md  README.rst   setup.cfg         statik.egg-info
root@localhost:/usr/local/statik-site# pip3 install -r  requirements.txt
root@localhost:/usr/local/statik-site# python3 setup.py install
root@localhost:/usr/local/statik-site# rm -rf thanethomson.com
root@localhost:/usr/local/statik-site# git clone https://github.com/thanethomson/blog thanethomson.com
Cloning into 'thanethomson.com'...
remote: Counting objects: 454, done.
remote: Compressing objects: 100% (369/369), done.
remote: Total 454 (delta 74), reused 453 (delta 73), pack-reused 0
Receiving objects: 100% (454/454), 2.77 MiB | 4.69 MiB/s, done.
Resolving deltas: 100% (74/74), done.
Checking connectivity... done.
root@localhost:/usr/local/statik-site# cd thanethomson.com
root@localhost:/usr/local/statik-site/thanethomson.com# ls
assets  bower.json  config-dev.yml  data  models  README.md  templates  views
root@localhost:/usr/local/statik-site/thanethomson.com# mv config-dev.yml config.yml
root@localhost:/usr/local/statik-site/thanethomson.com# statik 
it shows:
...
yaml.scanner.ScannerError: while scanning an anchor
  in "<unicode string>", line 1, column 8:
    title: &#27979;&#35797;1
           ^
expected alphabetic or numeric character, but found '#'
  in "<unicode string>", line 1, column 9:
    title: &#27979;&#35797;1
            ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/__init__.py", line 978, in emit
    msg = self.format(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 828, in format
    return fmt.format(record)
  File "/usr/lib/python3.4/logging/__init__.py", line 565, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.4/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/bin/statik", line 9, in <module>
    load_entry_point('statik==0.16.1', 'console_scripts', 'statik')()
  File "/usr/local/lib/python3.4/dist-packages/statik-0.16.1-py3.4.egg/statik/cmdline.py", line 113, in main
    logger.exception("Exception caught while attempting to generate project", e)
Message: 'Exception caught while attempting to generate project'
Arguments: (ScannerError('while scanning an anchor', <yaml.error.Mark object at 0x7f0cdc4924a8>, "expected alphabetic or numeric character, but found '#'", <yaml.error.Mark object at 0x7f0cdc492358>),)
root@localhost:/usr/local/statik-site/thanethomson.com#

the statik under python3 still doesn't support chinese posts.
how to fix it?
tks

**Comment by thanethomson** [comment]
What do you get when you run the following command?

```bash
locale
```

**Comment by luckypoem** [comment]
root@localhost:/usr/local/statik-site# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
root@localhost:/usr/local/statik-site#

**Comment by thanethomson** [comment]
Very strange. I can't figure this one out. It is actually supposed to work - let me post this on StackOverflow and see if someone else can help us out with this.

**Comment by luckypoem** [comment]
any update on stackoverflow? what's the url ?

**Comment by thanethomson** [comment]
Sorry for the delay again, been super busy the past few days.

I had some time to play around with it this morning and I think I figured it out. Keep your encoding as `utf8`, but then make sure if you use Chinese text in the YAML preamble (like the `title` field) make sure you quote it, as such:

```yaml
---
title: "测试1"   # quote these single-line strings
slug: test-1
summary: >
  点击标题，
  看全文。
date: 2017-04-07T21:00:00
tags:
  - tag1
  - tag2
  - tag3
---

这是测试1.

看看如何？
```

You don't need to quote the text for multi-line YAML strings (ones that start with the `>` character), or for the body of the post itself. It worked for me - try it out on your side and let me know?

**Comment by luckypoem** [comment]
now it's ok.the title's value should be always quoted.
thank u very very much for your efforts!
